

<div id='weather'>
	<div class='right' id="locationright">
		<?php echo ucfirst($this->city);?><br>
		<a onclick='changeLocation();' >Change location</a>
		<div id='locationChange' id='locationform'>
			<form name='locationdefault' action='/weather' method='POST'>
				<input type='text' value='' id='textlocation' name='textlocation'>
				<input type='submit' value='submit' type="submit"> 
				<a onclick='saveLocation();' > Save for the future &nbsp; 
				<a onclick='autoDetectLocation();' > AutoDetect &nbsp; 
				<a onclick='closeChangeLocation();' > Cancel</a>
			</form>
		</div>
	</div>


	<div class='right'> 
	<br>
	<?php echo $this->weather_today['currentTemperature']; ?>F&deg;
<?php echo $this->weather_today['currentWeather']; ?> 	<!-- <a onclick='showTomorrow();'>Tomorrow</a>
			<div id='weathertomorrow' style="display:none;">
			<a onclick='closeTomorrow();' >close</a><br>
			// <?php echo $this->tomorrowDay.'.  '?>
			
			<img src="<?php echo $this->tomorrowIcon; ?>" /><br>
			<?php echo $this->tomorrowWeather; ?>
			<br>min: <?php echo $this->tomorrowLow; ?>F&deg;
			max: <?php echo $this->tomorrowHigh; ?>F&deg;
			</div>
			 -->
	<div id="clear">
	</div>
	</div>	
</div>


